branches:
  - main
  - name: 3.x
    range: 3.x
  - name: 2.x
    range: 2.x
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  - - '@semantic-release/npm'
    - npmPublish: false  # Only update version, don't publish (we publish from dist/)
  - - '@semantic-release/git'
    - assets:
        - package.json
        - CHANGELOG.md
  - - '@semantic-release/github'
    - assets:
        - path: dist/*.tgz
          label: NPM Package
