name: Release
on:
  push:
    branches:
      - main
      - 3.x
      - 2.x
      - 1.x
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn --pure-lockfile
      - name: Build
        run: yarn build
      - name: Semantic Release
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          yarn release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          HUSKY: 0
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
