name: 'Security Scan'
on:
  pull_request:
  push:
  schedule:
    - cron: '22 16 * * 6'
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - name: Run CodeQL
        uses: github/codeql-action/analyze@v3
